#pragma once
#include "camera.h"
#include "material.h"
#include "color.h"
#include "sphere.h"
#include "moving_sphere.h"
#include "box.h"
#include "bvh.h"

#include <iostream>
#include <omp.h>
#include "constant_medium.h"
hittable_list two_perlin_spheres();
hittable_list random_scene();
hittable_list two_spheres();
hittable_list earth();
hittable_list simple_light();
hittable_list cornell_box();
hittable_list final_scene();
hittable_list cornell_smoke();